### ISSUE TITLE
Allow to post error message on failed backporting to PR

### ISSUE THREAD

**Issue by felixfontein** [sanitizers/patchback-github-app#13]
Currently there's only the failed Checks result, but that's hard to spot. With an error message posted as a comment to the PR, spotting errors is a lot easier. At least for people looking at notifications / emails :)

**Comment by webknjaz** [comment]
I believe https://github.com/sanitizers/patchback-github-app/commit/7652e9fc31d153214cebf3297ac8bf402bdc9949 + https://github.com/sanitizers/patchback-github-app/commit/12d485e350e58e4697bf08805fa4241da456e797 should improve this.
